language: objective-c
xcode_workspace: MBGeolocation.xcworkspace
osx_image: xcode8.2

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init

install:
  gem install xcpretty

script:
- set -o pipefail && xcodebuild -workspace MBGeolocation.xcworkspace -scheme 'MBGeolocation' -destination 'platform=iOS Simulator,OS=10.2,name=iPad Pro (9.7 inch)' -destination-timeout 120 clean build | xcpretty
- set -o pipefail && xcodebuild -workspace MBGeolocation.xcworkspace -scheme 'MBGeolocation' -destination 'platform=iOS Simulator,OS=10.2,name=iPad Pro (9.7 inch)' -destination-timeout 120 test | xcpretty
